# Generated by Django 2.0.13 on 2019-04-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenVillages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Nija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village', to='ninja.HiddenVillages')),
            ],
        ),
        migrations.CreateModel(
            name='NijaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('nija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ninja.Nija')),
            ],
        ),
    ]
