# Generated by Django 2.0.13 on 2019-04-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nijaimage',
            name='nija',
        ),
        migrations.RemoveField(
            model_name='nija',
            name='village',
        ),
        migrations.DeleteModel(
            name='HiddenVillages',
        ),
        migrations.DeleteModel(
            name='NijaImage',
        ),
    ]
